### ISSUE TITLE
Missing ports for macros

### ISSUE THREAD

**Issue by Taredon** [SeadexGmbH/yasmine#27]
In the current version of yasmine, some of the macros were not ported to the new method signature, thus any compilations will fail when these macros are used.

The missing macros are (respectively their SELECT variants):
- Y_BEHAVIOR_ACTION
- Y_GUARD_ACTION

This:
`[ this ]( const sxy::event& _event ){ SX_UNUSED_PARAMETER(_event); _action }`
should be replaced with
`[ this ]( const sxy::event& _event, sxy::event_collector& _event_collector ){ SX_UNUSED_PARAMETER(_event); SX_UNUSED_PARAMETER(_event_collector); _action }`

**Comment by SeadexTM** [comment]
Thank you for the input.
Fixed in yasmine 1.5.0.
