### ISSUE TITLE
yasmine.hpp references files that aren't installed

### ISSUE THREAD

**Issue by mjeronimo** [SeadexGmbH/yasmine#31]
@SeadexWP @SeadexTM 

After installing yasmine using 'make install' and trying to use the headers from /usr/local/include/yasmine, my code includes yasmine.hpp. However, yasmine.hpp attempts to include a few files that aren't present in /usr/local/include/yasmine (haven't been installed):

#include "backward_compatibility.hpp"

#include "essentials/compatibility/compatibility.hpp"
#include "essentials/compatibility/chrono.hpp"
#include "essentials/compatibility/thread.hpp"

These files should be included in the installation. It seems that the library hasn't been tested with sample code that accesses the library from /usr/local/include.

**Comment by SeadexWP** [comment]
Fixed in 1.5.2
