### ISSUE TITLE
Cmake fails on release 1.5.2

### ISSUE THREAD

**Issue by bperry730** [SeadexGmbH/yasmine#33]
Running `cmake -DCPP_VERSION=14 -DSX_NO_LOGGING=ON ..` caused a Cmake error for me citing "SX_ASSERT" was not defined.  Removing the `SX_NO_LOGGING` bit succeeds.  Can you reproduce with a clean build?

**Comment by SeadexWP** [comment]
Fixed in 1.5.3.
