### ISSUE TITLE
shallow history and deep history has been implemented actually the same?

### ISSUE THREAD

**Issue by siwifttiger** [SeadexGmbH/yasmine#37]
shallow_history_impl.cpp is the same with deep_histroy_impl.cpp,  but they are definitely different in UML definition. What's wrong with they two? Am I using them in wrong way?

**Comment by D-r-P-3-p-p-3-r** [comment]
There's nothing wrong with them. The difference is how they are treated e.g. in the transition algorithm which is implemented via the visitor pattern. Thus, the "different" code isn't within the history classes, but within the algorithm classes.
