### ISSUE TITLE
Compilation bug for g++

### ISSUE THREAD

**Issue by Taredon** [SeadexGmbH/yasmine#9]
Compiling yasmine with g++ (tested 4.9 and 5.4) with following compile commands

`cmake -G "Unix Makefiles" -DCMAKE_CXX_FLAGS=-m64 .`
`make`

fails with
`yasmine/yasmine/color_mapping.cpp: In member function ‘sxy::color sxy::color_mapping::get_color(sxy::log_level) const’:`
`yasmine/yasmine/color_mapping.cpp:68:16: error: ‘color’ is not a class, namespace, or enumeration
  color color = color::C_WHITE;`

Apparently the compiler tries to use the object 'color' instead of the class 'color' at this position.
Changing the name for the variable fixed compilation for me.

**Comment by SeadexWP** [comment]
Thanks for the bug report!
The variable will be renamed in the next release (1.0.0).

**Comment by SeadexWP** [comment]
Fixed in 1.0.0!
